Repository gnosis/gp-v2-services, pull requests merged in 2021-11, with the labels that each got.

#1225 Balancer: Stable Pools in Baseline Solver.
  shared/src/sources/balancer/pool_fetching.rs
  shared/src/sources/balancer/swap.rs
  shared/src/sources/balancer/swap/stable_math.rs
Labels: balancer-integration

#1339 Update ERC20 `transfer()` gas cost.
  shared/src/price_estimation/gas.rs
Labels: trivial

#1291 Update to Rust edition 2021
  alerter/Cargo.toml
  contracts/Cargo.toml
  e2e/Cargo.toml
  model/Cargo.toml
  orderbook/Cargo.toml
  shared/Cargo.toml
  shared/src/sources/balancer/graph_api.rs
  solver/Cargo.toml
Labels: trivial

#1367 Re-introduce driver wait time.
  e2e/tests/e2e/eth_integration.rs
  e2e/tests/e2e/onchain_settlement.rs
  e2e/tests/e2e/settlement_without_onchain_liquidity.rs
  e2e/tests/e2e/smart_contract_orders.rs
  e2e/tests/e2e/vault_balances.rs
  solver/src/driver.rs
  solver/src/main.rs
Labels: trivial

#1372 Adjust slippage for zeroEx Solver
  crates/shared/src/solver_utils.rs
  crates/solver/src/main.rs
  crates/solver/src/solver.rs
  crates/solver/src/solver/zeroex_solver.rs
Labels: merge when green

#1230 [Metrics] Surplus Reporting with outlier log.
  crates/solver/src/analytics.rs
  crates/solver/src/driver.rs
  crates/solver/src/lib.rs
  crates/solver/src/metrics.rs
  crates/solver/src/settlement.rs
  crates/solver/src/solver.rs
Labels: metrics

#1394 Log winning settlement name
  crates/solver/src/driver.rs
Labels: merge when green, trivial

#1397 Remove `get_spot_price` method
  crates/shared/src/baseline_solver.rs
  crates/shared/src/sources/balancer/swap.rs
  crates/shared/src/sources/uniswap/pool_fetching.rs
  crates/solver/src/solver/baseline_solver.rs
Labels: trivial

#1398 Rename Liquidity Protocols
  crates/e2e/tests/e2e/eth_integration.rs
  crates/e2e/tests/e2e/onchain_settlement.rs
  crates/e2e/tests/e2e/services.rs
  crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
  crates/e2e/tests/e2e/smart_contract_orders.rs
  crates/e2e/tests/e2e/vault_balances.rs
  crates/orderbook/src/main.rs
  crates/orderbook/src/metrics.rs
  crates/shared/src/bad_token/trace_call.rs
  crates/shared/src/baseline_solver.rs
  crates/shared/src/price_estimation/baseline.rs
  crates/shared/src/sources.rs
  crates/shared/src/sources/balancer_v2.rs
  crates/shared/src/sources/balancer_v2/event_handler.rs
  crates/shared/src/sources/balancer_v2/graph_api.rs
  crates/shared/src/sources/balancer_v2/info_fetching.rs
  crates/shared/src/sources/balancer_v2/pool_cache.rs
  crates/shared/src/sources/balancer_v2/pool_fetching.rs
  crates/shared/src/sources/balancer_v2/pool_init.rs
  crates/shared/src/sources/balancer_v2/pool_storage.rs
  crates/shared/src/sources/balancer_v2/swap.rs
  crates/shared/src/sources/balancer_v2/swap/error.rs
  crates/shared/src/sources/balancer_v2/swap/fixed_point.rs
  crates/shared/src/sources/balancer_v2/swap/fixed_point/logexpmath.rs
  crates/shared/src/sources/balancer_v2/swap/math.rs
  crates/shared/src/sources/balancer_v2/swap/stable_math.rs
  crates/shared/src/sources/balancer_v2/swap/weighted_math.rs
  crates/shared/src/sources/uniswap_v2.rs
  crates/shared/src/sources/uniswap_v2/pair_provider.rs
  crates/shared/src/sources/uniswap_v2/pool_cache.rs
  crates/shared/src/sources/uniswap_v2/pool_fetching.rs
  crates/solver/src/interactions.rs
  crates/solver/src/interactions/balancer_v2.rs
  crates/solver/src/interactions/uniswap_v2.rs
  crates/solver/src/liquidity.rs
  crates/solver/src/liquidity/balancer_v2.rs
  crates/solver/src/liquidity/uniswap_v2.rs
  crates/solver/src/liquidity_collector.rs
  crates/solver/src/main.rs
  crates/solver/src/metrics.rs
  crates/solver/src/solver/baseline_solver.rs
  crates/solver/src/solver/http_solver/settlement.rs
  crates/solver/src/solver/naive_solver/multi_order_solver.rs
Labels: trivial

#1401 fix wei from gwei
  crates/shared/src/arguments.rs
Labels: trivial

#1403 Separate uniswap like protocols
  crates/contracts/artifacts/HoneyswapFactory.json
  crates/contracts/artifacts/HoneyswapRouter.json
  crates/contracts/artifacts/IUniswapLikeFactory.json
  crates/contracts/artifacts/SushiSwapFactory.json
  crates/contracts/artifacts/SushiSwapRouter.json
  crates/contracts/artifacts/SushiswapV2Factory.json
  crates/contracts/artifacts/SushiswapV2Router02.json
  crates/contracts/build.rs
  crates/contracts/src/bin/vendor.rs
  crates/contracts/src/lib.rs
  crates/e2e/tests/e2e/eth_integration.rs
  crates/e2e/tests/e2e/onchain_settlement.rs
  crates/e2e/tests/e2e/services.rs
  crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
  crates/e2e/tests/e2e/smart_contract_orders.rs
  crates/e2e/tests/e2e/vault_balances.rs
  crates/orderbook/src/main.rs
  crates/shared/src/bad_token/trace_call.rs
  crates/shared/src/price_estimation/quasimodo.rs
  crates/shared/src/sources.rs
  crates/shared/src/sources/honeyswap.rs
  crates/shared/src/sources/sushiswap.rs
  crates/shared/src/sources/uniswap_v2.rs
  crates/shared/src/sources/uniswap_v2/pair_provider.rs
  crates/shared/src/sources/uniswap_v2/pool_fetching.rs
  crates/solver/src/main.rs
Labels: configuration change

#1423 Log orders that have solutions but don't get settled
  crates/solver/src/analytics.rs
  crates/solver/src/driver.rs
Labels: trivial

#1448 Add Balancer base pool factory ABI
  crates/contracts/artifacts/BalancerV2BasePoolFactory.json
  crates/contracts/build.rs
  crates/contracts/src/bin/vendor.rs
Labels: trivial

#1441 Rename some balancer pool fields
  crates/shared/src/sources/balancer_v2/graph_api.rs
  crates/shared/src/sources/balancer_v2/info_fetching.rs
  crates/shared/src/sources/balancer_v2/pool_cache.rs
  crates/shared/src/sources/balancer_v2/pool_fetching.rs
  crates/shared/src/sources/balancer_v2/pool_init.rs
  crates/shared/src/sources/balancer_v2/pool_storage.rs
  crates/shared/src/sources/balancer_v2/swap.rs
  crates/solver/src/liquidity/balancer_v2.rs
  crates/solver/src/solver/baseline_solver.rs
  crates/solver/src/solver/http_solver.rs
  crates/solver/src/solver/http_solver/settlement.rs
Labels: trivial

#1437 Fix Tenderly simulation block
  crates/solver/src/settlement_simulation.rs
Labels: trivial
