Repository gnosis/gp-v2-services, pull requests merged in 2021-05, with the labels that each got.

#537 Move test utilities and macros to a shared module
  model/src/order.rs
  orderbook/src/api/get_markets.rs
  solver/src/interactions.rs
  solver/src/interactions/erc20.rs
  solver/src/interactions/uniswap.rs
  solver/src/interactions/weth.rs
  solver/src/lib.rs
  solver/src/liquidity.rs
  solver/src/liquidity/offchain_orderbook.rs
  solver/src/liquidity/uniswap.rs
  solver/src/oneinch_solver.rs
  solver/src/oneinch_solver/api.rs
  solver/src/orderbook.rs
  solver/src/settlement/settlement_encoder.rs
  solver/src/testutil.rs
Labels: merge when green, trivial

#556 Separate reusable components in e2e test
  e2e/tests/onchain_settlement.rs
  e2e/tests/services.rs
Labels: merge when green

#547 SushiSwap Price Estimation
  contracts/artifacts/IUniswapLikePair.json
  contracts/build.rs
  contracts/src/bin/vendor.rs
  contracts/src/lib.rs
  e2e/tests/services.rs
  orderbook/src/main.rs
  shared/src/arguments.rs
  shared/src/lib.rs
  shared/src/pool_aggregating.rs
  shared/src/pool_fetching.rs
  shared/src/price_estimate.rs
  solver/src/main.rs
  solver/src/solver.rs
Labels: merge when green

#569 Make fee calculator eth aware
  e2e/tests/services.rs
  model/src/order.rs
  orderbook/src/api.rs
  orderbook/src/api/get_fee_info.rs
  orderbook/src/fee.rs
  orderbook/src/lib.rs
  orderbook/src/main.rs
  orderbook/src/orderbook.rs
  solver/src/driver.rs
  solver/src/liquidity/offchain_orderbook.rs
Labels: merge when green

#580 Default to creating 1Inch swap without splitting
  solver/src/oneinch_solver.rs
  solver/src/oneinch_solver/api.rs
Labels: merge when green

#614 Remove boilerplate for implementing `EventRetrieving` for contracts
  contracts/build.rs
  orderbook/src/database/events.rs
  orderbook/src/event_updater.rs
  shared/src/current_block.rs
  shared/src/event_handling.rs
Labels: merge when green

#620 Refactor build script to allow arbitrary config extensions
  contracts/build.rs
  orderbook/src/database/events.rs
  orderbook/src/event_updater.rs
Labels: merge when green

#633 [Hot Fix] Not all pools considered for estimate
  shared/src/price_estimate.rs
Labels: merge when green

#630 Add balancer vault artifact
  contracts/Cargo.toml
  contracts/artifacts/BalancerV2Vault.json
  contracts/artifacts/ERC20.json
  contracts/artifacts/ERC20Mintable.json
  contracts/artifacts/IUniswapLikePair.json
  contracts/artifacts/IUniswapLikeRouter.json
  contracts/artifacts/SushiswapV2Factory.json
  contracts/artifacts/SushiswapV2Pair.json
  contracts/artifacts/SushiswapV2Router02.json
  contracts/artifacts/UniswapV2Pair.json
  contracts/artifacts/WETH9.json
  contracts/build.rs
  contracts/src/bin/deploy.rs
  contracts/src/bin/vendor.rs
  contracts/src/lib.rs
Labels: merge when green

#649 No longer escape complexity level
  solver/src/oneinch_solver/api.rs
Labels: merge when green

#658 [Easy] Propogate EventHandler Maintenance Failure Logs
  orderbook/src/event_updater.rs
  shared/src/event_handling.rs
  shared/src/maintenance.rs
Labels: merge when green

#651 [Trivial] inconsistency in runtime arguments
  solver/src/main.rs
Labels: merge when green

#647 Disable private market makers for 1Inch solver
  solver/src/main.rs
  solver/src/oneinch_solver.rs
  solver/src/oneinch_solver/api.rs
  solver/src/solver.rs
Labels: merge when green

#641 Balancer Event Handling: Part I - Streaming
  orderbook/src/database/events.rs
  orderbook/src/database/orders.rs
  orderbook/src/database/trades.rs
  orderbook/src/main.rs
  shared/src/balancer_event_handler.rs
  shared/src/current_block.rs
  shared/src/event_handling.rs
  shared/src/lib.rs
Labels: merge when green

#671 [Easy] Include Solver Name in Simulation Failure
  solver/src/driver.rs
Labels: merge when green, oncall

#672 Add new bad token
  shared/src/bad_token/trace_call.rs
Labels: merge when green, trivial
