Repository gnosis/gp-v2-services, pull requests merged in 2021-07, with the labels that each got.

#804 [Easy] Update or reset inflight trades based on submission result
  solver/src/driver.rs
Labels: merge when green

#798 Move baseline liquidity sources to submodule
  e2e/tests/eth_integration.rs
  e2e/tests/onchain_settlement.rs
  e2e/tests/services.rs
  e2e/tests/settlement_without_onchain_liquidity.rs
  orderbook/src/main.rs
  orderbook/src/metrics.rs
  shared/src/arguments.rs
  shared/src/bad_token/trace_call.rs
  shared/src/baseline_solver.rs
  shared/src/lib.rs
  shared/src/price_estimate.rs
  shared/src/sources.rs
  shared/src/sources/balancer.rs
  shared/src/sources/balancer/event_handler.rs
  shared/src/sources/balancer/graph_api.rs
  shared/src/sources/balancer/info_fetching.rs
  shared/src/sources/balancer/pool_cache.rs
  shared/src/sources/balancer/pool_fetching.rs
  shared/src/sources/balancer/pool_init.rs
  shared/src/sources/balancer/pool_storage.rs
  shared/src/sources/balancer/swap.rs
  shared/src/sources/balancer/swap/error.rs
  shared/src/sources/balancer/swap/fixed_point.rs
  shared/src/sources/balancer/swap/fixed_point/logexpmath.rs
  shared/src/sources/balancer/swap/weighted_math.rs
  shared/src/sources/uniswap.rs
  shared/src/sources/uniswap/pair_provider.rs
  shared/src/sources/uniswap/pool_cache.rs
  shared/src/sources/uniswap/pool_fetching.rs
  solver/src/liquidity.rs
  solver/src/liquidity/balancer.rs
  solver/src/liquidity/uniswap.rs
  solver/src/main.rs
  solver/src/metrics.rs
  solver/src/solver/baseline_solver.rs
Labels: merge when green, trivial

#795 Make WeightedProductOrder implement BaselineSolvable
  shared/src/sources/balancer/swap.rs
  shared/src/sources/balancer/swap/fixed_point.rs
  solver/src/solver/baseline_solver.rs
Labels: merge when green

#796 Amm type for all on-chain liquidity
  solver/src/liquidity.rs
  solver/src/solver/baseline_solver.rs
Labels: merge when green

#813 [Easy] (de)serialization for BigRational as Decimal
  Cargo.lock
  model/Cargo.toml
  model/src/lib.rs
  model/src/ratio_as_decimal.rs
Labels: merge when green

#808 [HTTP solver] UpdatedAmmModel to new format
  solver/src/solver/http_solver.rs
  solver/src/solver/http_solver/model.rs
  solver/src/solver/http_solver/settlement.rs
Labels: merge when green

#821 Use full order execution for Match solver
  solver/src/solver/matcha_solver.rs
Labels: merge when green

#809 Solve with bal liquidity
  e2e/tests/eth_integration.rs
  e2e/tests/onchain_settlement.rs
  e2e/tests/settlement_without_onchain_liquidity.rs
  orderbook/src/main.rs
  shared/src/arguments.rs
  shared/src/sources.rs
  shared/src/sources/balancer.rs
  shared/src/sources/balancer/pool_init.rs
  solver/src/liquidity/balancer.rs
  solver/src/liquidity_collector.rs
  solver/src/main.rs
  solver/src/metrics.rs
Labels: merge when green

#810 Disable pool intiailzation for unsupported networks
  contracts/build.rs
  shared/src/sources/balancer/pool_fetching.rs
  shared/src/sources/balancer/pool_init.rs
  solver/src/main.rs
Labels: merge when green

#811 Fetch initial weighted pool data on-chain
  shared/src/sources/balancer/event_handler.rs
  shared/src/sources/balancer/pool_fetching.rs
  shared/src/sources/balancer/pool_init.rs
  shared/src/sources/balancer/pool_storage.rs
Labels: merge when green

#833 HTTP Solver - update response model
  solver/src/solver/http_solver.rs
  solver/src/solver/http_solver/model.rs
  solver/src/solver/http_solver/settlement.rs
Labels: merge when green

#834 Improve `Order` debug implementation
  Cargo.lock
  model/Cargo.toml
  model/src/order.rs
Labels: merge when green, trivial

#831 Consider pool limits in BaselineSolvable computation
  shared/src/price_estimate.rs
  shared/src/sources/uniswap/pool_fetching.rs
Labels: merge when green

#846 Fix pool maximum amount
  shared/src/sources/uniswap/pool_fetching.rs
Labels: merge when green

#840 [Balancer] BaselineSolvable - Check in/out amounts can be reciprocated
  shared/src/sources/balancer/swap.rs
  solver/src/solver/baseline_solver.rs
Labels: merge when green

#916 Add skipped migration
  database/sql/V010__skipped.sql
Labels: trivial
