Repository gnosis/gp-v2-services, pull requests merged in 2021-10, with the labels that each got.

#1185 Use stable `muslrust` again
  docker/Dockerfile.binary
Labels: merge when green, trivial

#1176 Independent logic for Partial and Full OrderValidation
  e2e/tests/services.rs
  model/src/order.rs
  orderbook/src/api.rs
  orderbook/src/api/create_order.rs
  orderbook/src/api/order_validation.rs
  orderbook/src/api/validation.rs
  orderbook/src/main.rs
  orderbook/src/orderbook.rs
  shared/src/bad_token/mod.rs
Labels: refactor

#1155 Fee&Quote Endpoint: Implemention with legacy logic.
  e2e/tests/services.rs
  orderbook/openapi.yml
  orderbook/src/api.rs
  orderbook/src/api/create_order.rs
  orderbook/src/api/get_fee_and_quote.rs
  orderbook/src/api/get_fee_info.rs
  orderbook/src/api/order_validation.rs
  orderbook/src/api/post_quote.rs
  orderbook/src/lib.rs
  orderbook/src/main.rs
Labels: api

#1256 Fix quote to use sell amount after fees.
  orderbook/src/api/post_quote.rs
Labels: easy

#1262 Fix the `POST v1/quote` metric label
  orderbook/src/api.rs
Labels: merge when green, trivial

#1271 Override dependabot
  Cargo.lock
  model/Cargo.toml
  orderbook/Cargo.toml
  shared/Cargo.toml
  solver/Cargo.toml
Labels: easy
