Repository gnosis/gp-v2-services, pull requests merged in 2021-08, with the labels that each got.

#923 Limit the gas for simulation transactions
  solver/src/settlement_simulation.rs
Labels: merge when green

#919 [Temporary] Reject New Order Sell/Buy Token Source/Destination
  orderbook/openapi.yml
  orderbook/src/api/create_order.rs
  orderbook/src/orderbook.rs
Labels: merge when green

#926 Fix E2E crate lints
  e2e/tests/services.rs
Labels: merge when green, trivial

#934 Retrieve buffers for instance submission
  shared/src/token_info.rs
  solver/src/solver.rs
  solver/src/solver/http_solver.rs
  solver/src/solver/http_solver/buffers.rs
Labels: merge when green

#944 Fix OpenAPI sell and buy token balance property names
  orderbook/openapi.yml
Labels: merge when green, trivial

#951 Reject orders selling WETH for ETH
  e2e/tests/services.rs
  orderbook/src/main.rs
  orderbook/src/orderbook.rs
Labels: merge when green

#953 Allow 'null' ref-token in HTTP solver settlements
  solver/src/solver/http_solver/model.rs
  solver/src/solver/http_solver/settlement.rs
Labels: merge when green, trivial

#955 Pass deadline into solvers
  shared/src/lib.rs
  solver/src/driver.rs
  solver/src/main.rs
  solver/src/solver.rs
  solver/src/solver/baseline_solver.rs
  solver/src/solver/http_solver.rs
  solver/src/solver/naive_solver.rs
  solver/src/solver/single_order_solver.rs
Labels: merge when green

#973 Drop default impl for solver name, small documentation changes
  solver/src/solver.rs
Labels: trivial

#958 Added support for Balancer Vault external balances
  e2e/tests/services.rs
  orderbook/src/account_balances.rs
  orderbook/src/main.rs
  orderbook/src/orderbook.rs
  shared/src/lib.rs
Labels: merge when green

#959 Implement utility for granting Vault roles to a relayer
  contracts/src/lib.rs
  contracts/src/vault.rs
  orderbook/src/account_balances.rs
Labels: merge when green

#985 Remove banneduser error in favour of existing forbidden error
  orderbook/openapi.yml
  orderbook/src/api/create_order.rs
  orderbook/src/orderbook.rs
Labels: merge when green, trivial

#993 Log settlement transaction hash
  solver/src/driver.rs
  solver/src/settlement_submission.rs
  solver/src/settlement_submission/public_mempool.rs
  solver/src/settlement_submission/retry.rs
Labels: merge when green, trivial

#997 Balancer Stable Pools part 1: contract artifacts
  contracts/artifacts/BalancerV2StablePool.json
  contracts/artifacts/BalancerV2StablePoolFactory.json
  contracts/build.rs
  contracts/src/bin/vendor.rs
  contracts/src/lib.rs
Labels: balancer-integration

#1003 Balancer Stable Pool Part 2 - Fetch Stable Pools with graph api
  shared/src/sources/balancer/graph_api.rs
  shared/src/sources/balancer/pool_init.rs
  shared/src/sources/balancer/pool_storage.rs
Labels: balancer-integration

#994 Don't alert on failed simulations
  solver/src/driver.rs
  solver/src/metrics.rs
Labels: merge when green

#999 Reorganize in preparation for new signature type
  e2e/tests/eth_integration.rs
  e2e/tests/onchain_settlement.rs
  e2e/tests/settlement_without_onchain_liquidity.rs
  e2e/tests/vault_balances.rs
  model/src/lib.rs
  model/src/order.rs
  model/src/signature.rs
  orderbook/src/api/cancel_order.rs
  orderbook/src/api/create_order.rs
  orderbook/src/database/orders.rs
  solver/src/encoding.rs
  solver/src/settlement.rs
  solver/src/solver/naive_solver/multi_order_solver.rs
Labels: merge when green
