Repository gnosis/gp-v2-services, pull requests merged in 2021-06, with the labels that each got.

#680 Use camel case for order cancellation serialization
  model/src/order.rs
  orderbook/src/api/cancel_order.rs
Labels: merge when green

#684 Reject orders with receivers as SC wallets
  e2e/tests/services.rs
  model/src/order.rs
  orderbook/openapi.yml
  orderbook/src/api/create_order.rs
  orderbook/src/main.rs
  orderbook/src/orderbook.rs
  shared/src/lib.rs
  shared/src/web3_traits.rs
Labels: merge when green

#573 [Easy] Doument Solver Trait
  shared/src/pool_fetching.rs
  solver/src/baseline_solver.rs
  solver/src/settlement/settlement_encoder.rs
  solver/src/solver.rs
Labels: merge when green

#707 Move files to their final location
  shared/src/lib.rs
  shared/src/pool_cache.rs
  shared/src/pool_cache_new.rs
  shared/src/recent_block_cache.rs
Labels: trivial

#706 Refactor pool cache to be generic to any kind of on-chain data
  e2e/tests/services.rs
  model/src/lib.rs
  orderbook/src/main.rs
  shared/src/lib.rs
  shared/src/pool_aggregating.rs
  shared/src/pool_cache.rs
  shared/src/pool_fetching.rs
  shared/src/price_estimate.rs
  shared/src/recent_block_cache.rs
  solver/src/driver.rs
  solver/src/liquidity/uniswap.rs
  solver/src/liquidity_collector.rs
  solver/src/main.rs
Labels: merge when green

#725 [Balancer] Batch and fetch scaling factors for Weighted Pool Data
  shared/src/balancer/event_handler.rs
  shared/src/balancer/pool_fetching.rs
Labels: balancer-integration, merge when green

#727 Add generic subgraph client
  Cargo.lock
  shared/Cargo.toml
  shared/src/lib.rs
  shared/src/subgraph.rs
Labels: merge when green

#737 Include Swap Fee in Balancer Pool Fetching
  shared/src/balancer/pool_fetching.rs
  shared/src/balancer/pool_storage.rs
Labels: merge when green

#738 Rework Balancer contract error enum
  shared/src/balancer.rs
  shared/src/balancer/swap.rs
  shared/src/balancer/swap/error.rs
  shared/src/balancer/swap/fixed_point.rs
  shared/src/balancer/swap/fixed_point/logexpmath.rs
Labels: merge when green

#740 Add Balancer fixed point numbers
  shared/src/balancer/swap/error.rs
  shared/src/balancer/swap/fixed_point.rs
Labels: merge when green

#742 Add helper function to compute Balancer traded amounts
  shared/src/balancer/swap.rs
  shared/src/balancer/swap/error.rs
  shared/src/balancer/swap/weighted_math.rs
Labels: merge when green

#751 Balancer weighted pool Graph query
  Cargo.lock
  shared/Cargo.toml
  shared/src/balancer.rs
  shared/src/balancer/graph_api.rs
  shared/src/balancer/swap.rs
  shared/src/conversions.rs
  shared/src/event_handling.rs
  shared/src/macros.rs
  shared/src/subgraph.rs
Labels: merge when green

#755 Implement BaselineSolvable for Balancer's WeightedPool
  shared/src/balancer/graph_api.rs
  shared/src/balancer/info_fetching.rs
  shared/src/balancer/pool_storage.rs
  shared/src/balancer/swap.rs
  shared/src/balancer/swap/fixed_point.rs
  shared/src/balancer/swap/weighted_math.rs
Labels: merge when green

#758 [Easy] Cleanup Balancer Module
  shared/src/balancer/event_handler.rs
  shared/src/balancer/info_fetching.rs
  shared/src/balancer/pool_cache.rs
  shared/src/balancer/pool_fetching.rs
  shared/src/balancer/pool_storage.rs
  shared/src/balancer/swap.rs
  shared/src/balancer/swap/weighted_math.rs
Labels: merge when green

#770 [Easy-Refactor] Rename AmmOrder to ConstantProductOrder
  solver/src/driver.rs
  solver/src/liquidity.rs
  solver/src/liquidity/uniswap.rs
  solver/src/liquidity_collector.rs
  solver/src/solver.rs
  solver/src/solver/baseline_solver.rs
  solver/src/solver/http_solver.rs
  solver/src/solver/http_solver/settlement.rs
  solver/src/solver/naive_solver.rs
  solver/src/solver/naive_solver/multi_order_solver.rs
Labels: merge when green

#762 Differentiate Balancer pools by factory address
  shared/src/balancer/graph_api.rs
Labels: merge when green

#774 Add component for Balancer pool initialization
  shared/src/balancer.rs
  shared/src/balancer/pool_init.rs
Labels: merge when green

#777 Use pool initialization to populate pool storage
  shared/src/balancer/event_handler.rs
  shared/src/balancer/pool_fetching.rs
  shared/src/balancer/pool_init.rs
  shared/src/balancer/pool_storage.rs
Labels: merge when green

#780 Implement Balancer swap given out interaction
  Cargo.lock
  solver/Cargo.toml
  solver/src/interactions.rs
  solver/src/interactions/balancer.rs
Labels: merge when green

#783 Better logging for single-order solvers
  solver/src/solver/oneinch_solver/api.rs
  solver/src/solver/paraswap_solver/api.rs
  solver/src/solver/single_order_solver.rs
Labels: merge when green

#784 Refactor transport modules to move dummy Web3 to shared
  orderbook/src/main.rs
  orderbook/src/metrics.rs
  shared/src/lib.rs
  shared/src/macros.rs
  shared/src/transport.rs
  shared/src/transport/dummy.rs
  shared/src/transport/http.rs
  shared/src/transport/instrumented.rs
  solver/src/interactions/balancer.rs
  solver/src/interactions/erc20.rs
  solver/src/interactions/uniswap.rs
  solver/src/interactions/weth.rs
  solver/src/lib.rs
  solver/src/liquidity.rs
  solver/src/liquidity/offchain_orderbook.rs
  solver/src/liquidity/uniswap.rs
  solver/src/main.rs
  solver/src/metrics.rs
  solver/src/orderbook.rs
  solver/src/settlement/settlement_encoder.rs
  solver/src/solver/oneinch_solver.rs
  solver/src/solver/paraswap_solver.rs
Labels: merge when green, trivial

#785 Add a mock transport
  shared/src/transport.rs
  shared/src/transport/mock.rs
Labels: merge when green

#789 Paraswap query input logging
  solver/src/solver/paraswap_solver.rs
  solver/src/solver/paraswap_solver/api.rs
Labels: merge when green

#786 Add allowance manager component
  shared/src/transport/mock.rs
  solver/src/interactions.rs
  solver/src/interactions/allowances.rs
Labels: merge when green

#793 Use new allowance manager component
  solver/src/interactions/allowances.rs
  solver/src/interactions/uniswap.rs
  solver/src/liquidity/uniswap.rs
  solver/src/main.rs
  solver/src/solver.rs
  solver/src/solver/oneinch_solver.rs
  solver/src/solver/oneinch_solver/api.rs
  solver/src/solver/paraswap_solver.rs
Labels: merge when green

#794 Added balancer liquidity provider for solvers
  shared/src/balancer/pool_cache.rs
  shared/src/balancer/pool_fetching.rs
  shared/src/balancer/pool_storage.rs
  shared/src/balancer/swap.rs
  shared/src/baseline_solver.rs
  shared/src/price_estimate.rs
  solver/src/liquidity.rs
  solver/src/liquidity/balancer.rs
  solver/src/liquidity/uniswap.rs
  solver/src/solver/baseline_solver.rs
Labels: merge when green
