Repository gnosis/gp-v2-services, pull requests merged in 2021-09, with the labels that each got.

#1006 [Easy] Balancer Stable Pool part 3: Info Fetching
  Cargo.lock
  shared/Cargo.toml
  shared/src/sources/balancer/info_fetching.rs
  shared/src/sources/balancer/pool_fetching.rs
  shared/src/sources/balancer/pool_init.rs
  shared/src/sources/balancer/pool_storage.rs
Labels: balancer-integration, easy

#1060 Add metrics for account balance updates
  e2e/tests/services.rs
  orderbook/src/account_balances.rs
  orderbook/src/main.rs
  orderbook/src/metrics.rs
Labels: trivial

#1063 Fix match condition for signature recovery
  orderbook/src/orderbook.rs
Labels: merge when green

#1064 [Easy] rework RegisteredPool for maintainability
  shared/src/sources/balancer/graph_api.rs
  shared/src/sources/balancer/pool_cache.rs
  shared/src/sources/balancer/pool_fetching.rs
  shared/src/sources/balancer/pool_init.rs
  shared/src/sources/balancer/pool_storage.rs
Labels: balancer-integration

#1008 [Easy] Balancer Stable Pool part 5: Structural Refactoring
  shared/src/sources/balancer/pool_cache.rs
  shared/src/sources/balancer/pool_fetching.rs
  shared/src/sources/balancer/swap.rs
  solver/src/liquidity.rs
  solver/src/liquidity/balancer.rs
  solver/src/metrics.rs
  solver/src/solver/baseline_solver.rs
  solver/src/solver/http_solver.rs
  solver/src/solver/http_solver/settlement.rs
Labels: balancer-integration, easy

#998 Balancer Stable Pools part 6: Pool Fetching
  shared/src/sources/balancer/pool_cache.rs
  shared/src/sources/balancer/pool_fetching.rs
  shared/src/sources/balancer/pool_storage.rs
  solver/src/liquidity/balancer.rs
Labels: balancer-integration

#992 Stable Pools part 7: Forward Pools to HTTP solver.
  solver/src/interactions/allowances.rs
  solver/src/liquidity.rs
  solver/src/liquidity/balancer.rs
  solver/src/liquidity_collector.rs
  solver/src/solver/baseline_solver.rs
  solver/src/solver/http_solver.rs
  solver/src/solver/http_solver/model.rs
  solver/src/solver/http_solver/settlement.rs
Labels: balancer-integration

#1078 Also report simluation failure on latest for settlements that failed on liquidity fetching block.
  solver/src/driver.rs
Labels: merge when green, trivial

#1090 Implement dry run settlement submission.
  Cargo.lock
  solver/Cargo.toml
  solver/src/main.rs
  solver/src/settlement_submission.rs
  solver/src/settlement_submission/dry_run.rs
Labels: merge when green, trivial

#1073 pending_transaction support for Erigon
  solver/src/pending_transactions.rs
Labels: merge when green

#1096 Cargo update
  Cargo.lock
Labels: trivial

#1143 New fee and amount quote API
  orderbook/openapi.yml
  orderbook/src/api.rs
  orderbook/src/api/post_quote.rs
Labels: merge when green

#1127 Balancer Baseline Stable Math
  shared/src/sources/balancer/swap.rs
  shared/src/sources/balancer/swap/error.rs
  shared/src/sources/balancer/swap/fixed_point.rs
  shared/src/sources/balancer/swap/math.rs
  shared/src/sources/balancer/swap/stable_math.rs
Labels: balancer-integration

#1161 Adding new enforced uniform clearing price flag for quasimodo
  solver/src/solver.rs
  solver/src/solver/http_solver.rs
Labels: merge when green

#1169 Pre-Order Validation
  e2e/tests/services.rs
  orderbook/src/api.rs
  orderbook/src/api/create_order.rs
  orderbook/src/api/validation.rs
  orderbook/src/main.rs
  orderbook/src/orderbook.rs
Labels: refactor
