Repository gnosis/gp-v2-services, pull requests merged in 2021-12, with the labels that each got.

#1450 Add Balancer event indexing manual test
  crates/contracts/build.rs
  crates/contracts/src/lib.rs
  crates/shared/src/sources/balancer_v2/event_handler.rs
  crates/shared/src/sources/balancer_v2/pool_init.rs
Labels: trivial

#1451 Add Balancer `BasePool` ABI
  crates/contracts/artifacts/BalancerV2BasePool.json
  crates/contracts/build.rs
  crates/contracts/src/bin/vendor.rs
  crates/contracts/src/lib.rs
Labels: trivial

#1457 Use integer seconds for HTTP solver timelimit.
  crates/shared/src/http_solver_api.rs
Labels: merge when green, trivial

#1418 Introduce `testlib` crate with things common for tests
  Cargo.lock
  crates/orderbook/Cargo.toml
  crates/orderbook/src/api/get_markets.rs
  crates/shared/Cargo.toml
  crates/shared/src/bad_token/trace_call.rs
  crates/shared/src/paraswap_api.rs
  crates/shared/src/price_estimation/paraswap.rs
  crates/shared/src/price_estimation/quasimodo.rs
  crates/shared/src/price_estimation/zeroex.rs
  crates/shared/src/sources/sushiswap.rs
  crates/shared/src/sources/uniswap_v2.rs
  crates/shared/src/sources/uniswap_v2/pair_provider.rs
  crates/shared/src/token_list.rs
  crates/shared/src/zeroex_api.rs
  crates/solver/Cargo.toml
  crates/solver/src/solver/oneinch_solver.rs
  crates/solver/src/solver/oneinch_solver/api.rs
  crates/solver/src/solver/paraswap_solver.rs
  crates/solver/src/solver/zeroex_solver.rs
  crates/testlib/Cargo.toml
  crates/testlib/src/lib.rs
  crates/testlib/src/tokens.rs
Labels: cleanup

#1474 [easy] Adding cow-dex-ag solver
  crates/solver/src/main.rs
  crates/solver/src/solver.rs
Labels: merge when green

#1486 Remove `event_handler` module
  crates/shared/src/sources/balancer_v2.rs
  crates/shared/src/sources/balancer_v2/event_handler.rs
  crates/shared/src/sources/balancer_v2/pool_fetching.rs
  crates/shared/src/sources/balancer_v2/pool_storage.rs
Labels: trivial

#1497 Update Balancer cache
  crates/shared/src/sources/balancer_v2/pool_fetching/cache.rs
Labels: trivial

#1503 Adds new mipsolver_uses_internal_buffers parameter.
  crates/shared/src/arguments.rs
  crates/solver/src/main.rs
  crates/solver/src/solver.rs
Labels: trivial
